spring.application.name=pizzaspring
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}
server.servlet.context-path=/api

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
# Hibernate; update / create-drop
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

api.key=${API_KEY}
api.secret=${API_SECRET}

# swagger-ui custom path
springdoc.swagger-ui.path=/swagger-ui.html

# Sovrapprezzo value
ordine.prioritario.sovrapprezzo=2.50
